spring:
  application:
    name: "sample-api-gateway"
  cloud:
    gateway:
      routes:
        - id: "users-status-check"
          uri: "http://localhost:8083"
          predicates:
            - "Path=/users/status/check"
            - "Method=GET"
          filters:
            - "RemoveRequestHeader=Cookie"
        - id: "albums"
          uri: "http://localhost:8084"
          predicates:
            - "Path=/albums"
            - "Method=GET"
          filters:
            - "RemoveRequestHeader=Cookie"
        - id: "photos"
          uri: "http://localhost:8085"
          predicates:
            - "Path=/photos"
            - "Method=GET"
          filters:
            - "RemoveRequestHeader=Cookie"
server:
  port: "8081"