spring:
  application:
    name: "sample-api-gateway"
  cloud:
    gateway:
      routes:
        - id: "users-status-check"
          uri: "lb://sample-resource-server"
          predicates:
            - "Path=/users/**"
          filters:
            - "RemoveRequestHeader=Cookie"
        - id: "albums"
          uri: "lb://albums-resource-server"
          predicates:
            - "Path=/albums"
            - "Method=GET"
          filters:
            - "RemoveRequestHeader=Cookie"
        - id: "photos"
          uri: "lb://photos-resource-server"
          predicates:
            - "Path=/photos"
            - "Method=GET"
          filters:
            - "RemoveRequestHeader=Cookie"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka
server:
  port: "8081"